#!/bin/bash
#	hooks/EXAMPLES/SAST-permission-775-001  3.381.620  2019-08-20T15:20:47.236752-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.380  
#	   testing return code from test case 
#	hooks/EXAMPLES/SAST-permission-775-001  3.334.571  2019-08-18T00:04:32.376157-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.333-1-gfdd1a29  
#	   initial commit 
#	hooks/TEST/pre-commit/SAST-permission-001  3.301.527  2019-08-16T16:32:32.032546-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.300-1-gf8a6c29  
#	   hooks/pre-commit  added SAST test cases for pre-commit 
### production standard 3.0 shellcheck
### production standard 5.1.160 Copyright
#       Copyright (c) 2019 Bradley Allen
#       MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
BOLD=$(tput -Txterm bold)
NORMAL=$(tput -Txterm sgr0)
###	Place test case here

if [ -g "${1}" ] ; then
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: FILE exists and its set-group-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
	exit 1
fi
if [ -u "${1}" ] ; then
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: FILE exists and its set-user-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
	exit 1
fi
if [ -k "${1}" ] ; then	#	no effect on files, directory, all files in directory will be modifiable only by their owners (example /tmp)
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - directory permission: FILE exists and has its sticky bit set - ${BOLD}FAIL - FAIL${NORMAL}"
	exit 1
fi
#       Verify file permissions
if [ $(stat -Lc %a "${1}") == 775 ]; then
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: check mode - ${BOLD}PASS - PASS${NORMAL}"
	exit 0
else
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: check mode - ${BOLD}FAIL - FAIL${NORMAL}"
	exit 1
fi
exit 124
###
