#!/bin/bash
#	hooks/EXAMPLES/TEST/FVT-option-usage-001/SAST-permission-001  3.319.550  2019-08-17T10:47:45.487571-05:00 (CDT)  https://github.com/BradleyA/user-files.git  uadmin  one-rpi3b.cptx86.com 3.318  
#	   FVT-option-usage-001   added SAST test cases 
### production standard 3.0 shellcheck
### production standard 5.1.160 Copyright
#       Copyright (c) 2019 Bradley Allen
#       MIT License is in the online DOCUMENTATION, DOCUMENTATION URL defined below.
BOLD=$(tput -Txterm bold)
NORMAL=$(tput -Txterm sgr0)
###	Place test case here

#       Verify file permissions
if [ $(stat -Lc %a "${1}") == 755 ]; then
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: check mode - ${BOLD}PASS - PASS${NORMAL}"
else
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: check mode - ${BOLD}FAIL - FAIL${NORMAL}"
fi
if [ -g "${1}" ] ; then
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: FILE exists and its set-group-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
fi
if [ -u "${1}" ] ; then
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - file permission: FILE exists and its set-user-ID bit is set - ${BOLD}FAIL - FAIL${NORMAL}"
fi
if [ -k "${1}" ] ; then	#	no effect on files, directory, all files in directory will be modifiable only by their owners (example /tmp)
	echo "${BOLD}Test case --->${NORMAL} ${0} ${1} ${RETURN_CODE} - directory permission: FILE exists and has its sticky bit set - ${BOLD}FAIL - FAIL${NORMAL}"
fi
##
